apiVersion: v1
kind: Service
metadata:
  name: npmapp
  labels:
    app: npmapp
spec:
  ports:
    - port: 8180
      targetPort: 8180
  selector:
    app: npmapp
  type: NodePort

  ---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: npmapp
spec:
  serviceName: "npmapp"
  replicas: 3
  selector:
    matchLabels:
      app: npmapp
  template:
    metadata:
      labels:
        app: npmapp
    spec:
      containers:
      - name: npmapp
        image: bodr1982/npmtest
        ports:
        - containerPort: 80
          name: npmapp
      - name: mysql
        env:
        - name: "MYSQL_USER"
          value: "root"
        - name: "MYSQL_ROOT_PASSWORD"
          value: "12345a"
        - name: "MYSQL_DATABASE"
          value: "test"
        image: mysql
        ports:
        - name: mysql
          containerPort: 3306
        resources: {}
      - name: adminer
        image: adminer
        ports:
        - containerPort: 8080
          name: adminer
